### ISSUE TITLE
Error during startup wrong version targeted

### ISSUE THREAD

**Issue by ripsnortntear** [erkle64/ValheimMods#1]
Hello, I get this error during startup

`[Warning:   BepInEx] Plugin [Plateautem 0.3.2] targets a wrong version of BepInEx (5.4.21.0) and might not work until you update`

I was looking in the repo to find the version target but im not versed enough to be able to locate it.

**Comment by erkle64** [comment]
Thanks.  Fixed in 0.3.3.
