### ISSUE TITLE
Can't add tools

### ISSUE THREAD

**Issue by SealviewTW** [erkle64/ValheimMods#2]
Valheim version 0.216.9
Mod version 0.3.3
![CannotAddTools](https://github.com/erkle64/ValheimMods/assets/11609472/cdd681a8-8d9c-431f-9484-49539afa8184)

**Comment by PrimeVoid** [comment]
Did you find out what happened?

**Comment by erkle64** [comment]
Hi, thanks for the report and sorry I missed it the first time.
I've been able to replicate the error and I've uploaded a new version to Thunderstore.  Seems to be working again for me, hopefully it works for you.
