### ISSUE TITLE
Hilder Update broke material insertion

### ISSUE THREAD

**Issue by Ruvanal** [erkle64/ValheimMods#5]
Tested in world and pack with only this mod and required dependencies.

The totem could be placed and a hoe inserted and removed.  But trying to insert stone, resin, wood would only generate the message to use the 'E" key; but the E would not actually insert the materials into the totem.  The log had this error message.

[Error  : Unity Log] MissingMethodException: bool Location.IsInside(UnityEngine.Vector3,single)
Stack trace:
Plateautem.Plateautem.Update () (at <28fcedc0a0644fa49b33c37b1a0796e5>:0)

**Comment by lessagg** [comment]
I had the same problem here. For God sake, give us back this mod working :X

**Comment by erkle64** [comment]
Updated and uploaded to Thunderstore.  Thanks for the report.
