### ISSUE TITLE
Bog Witch Update

### ISSUE THREAD

**Issue by Albarcelos** [erkle64/ValheimMods#7]
The mod is not working after the Bog Witch Update.

List of mods ON
![image](https://github.com/user-attachments/assets/06f5d517-f2d7-41db-a2f1-df5f79cd73b4)

In game error
![image](https://github.com/user-attachments/assets/c55a7dd9-eaa1-420d-80de-afbf99f70955)

**Comment by erkle64** [comment]
Thanks for the report.  Fixed in v0.3.8
